name: Docker Image CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container_name: ${COMPOSE_PROJECT_NAME}_dashboard
    hostname: ${COMPOSE_PROJECT_NAME}_dashboard
    restart: always
    ports: 
      - 5000:80
    networks:
      - network 
    steps:
        uses: actions/checkout@v2
        name: Build the Docker image
        run: docker build . --file Dockerfile --tag python-docker
           docker run python-docker
           docker run --publish 5000:5000 python-docker
           curl localhost:5000

      
